#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
  path:       /login
  controller: App\Controller\AuthenticationController::login
  methods:    GET|POST

app_logout:
  path:       /logout
  controller: App\Controller\AuthenticationController::logout

app_register:
  path:       /register
  controller: App\Controller\RegistrationController::register
  methods:    GET|POST

profile:
  path:       /profile
  controller: App\Controller\ProfileController::index
  methods:    GET

index_redirect:
  path:       /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'course_index'
    permanent: true
    keepRequestMethod: true

course_index:
  path:       /courses
  controller: App\Controller\CourseController::index
  methods:    GET

# admin
course_new:
  path:       /courses/new
  controller: App\Controller\CourseController::new
  methods:    GET|POST

# admin
course_edit:
  path:       /courses/{id}/edit
  controller: App\Controller\CourseController::edit
  methods:    GET|POST

# admin
course_delete:
  path:       /courses/{id}
  controller: App\Controller\CourseController::delete
  methods:    POST

course_show:
  path:       /courses/{id}
  controller: App\Controller\CourseController::show
  methods:    GET


# admin
lesson_new:
  path:       /lesson/new
  controller: App\Controller\LessonController::new
  methods:    GET|POST

# admin
lesson_edit:
  path:       /lesson/{id}/edit
  controller: App\Controller\LessonController::edit
  methods:    GET|POST

# admin
lesson_delete:
  path:       /lesson/{id}
  controller: App\Controller\LessonController::delete
  methods:    POST

lesson_show:
  path:       /lesson/{id}
  controller: App\Controller\LessonController::show
  methods:    GET

